# Generated by Django 6.0.5 on 2026-05-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Ready to Wear', 'Ready to Wear'), ('Unstitched', 'Unstitched'), ('Luxe Edition', 'Luxe Edition'), ('Embroidered', 'Embroidered'), ('Accessories', 'Accessories'), ('Jewelry', 'Jewelry')], default='Ready to Wear', max_length=50),
        ),
    ]
