# Generated by Django 4.2.8 on 2026-05-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('bg_image', models.ImageField(upload_to='banners/')),
                ('left_image', models.ImageField(blank=True, upload_to='banners/')),
                ('right_image', models.ImageField(blank=True, upload_to='banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'ordering': ['-created_at'],
            },
        ),
    ]
