# Generated by Django 6.0.5 on 2026-05-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_herobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
