# Generated by Django 6.0.5 on 2026-05-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_article_no_product_volume_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
