# Generated by Django 6.0.5 on 2026-05-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('order', 'Order Inquiry'), ('return', 'Return/Exchange'), ('product', 'Product Question'), ('feedback', 'Feedback'), ('other', 'Other')], default='other', max_length=20)),
                ('message', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('customer', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('product', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='processing', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Ready to Wear', 'Ready to Wear'), ('Unstitched', 'Unstitched'), ('Luxe Edition', 'Luxe Edition'), ('Embroidered', 'Embroidered'), ('Accessories', 'Accessories')], default='Ready to Wear', max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('image', models.URLField(max_length=500)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Binlibaas', max_length=100)),
                ('email', models.EmailField(default='admin@binlibaas.com', max_length=254)),
                ('phone', models.CharField(default='0300-7904231', max_length=20)),
                ('whatsapp', models.CharField(default='03230000883', max_length=20)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('address', models.TextField(default='Opposite GC University, Kotwali Road, Faisalabad')),
            ],
            options={
                'verbose_name': 'Store Settings',
            },
        ),
    ]
